"""Veritas streaming pipeline — PySpark schemas for Zeek JSON log types."""

from pyspark.sql.types import (
    ArrayType,
    DoubleType,
    LongType,
    StringType,
    StructField,
    StructType,
)

# ── conn.log ──────────────────────────────────────────────────────────────────
CONN_SCHEMA = StructType([
    StructField("ts", DoubleType()),
    StructField("uid", StringType()),
    StructField("id.orig_h", StringType()),
    StructField("id.orig_p", LongType()),
    StructField("id.resp_h", StringType()),
    StructField("id.resp_p", LongType()),
    StructField("proto", StringType()),
    StructField("service", StringType()),
    StructField("duration", DoubleType()),
    StructField("orig_bytes", LongType()),
    StructField("resp_bytes", LongType()),
    StructField("conn_state", StringType()),
    StructField("local_orig", StringType()),
    StructField("local_resp", StringType()),
    StructField("missed_bytes", LongType()),
    StructField("history", StringType()),
    StructField("orig_pkts", LongType()),
    StructField("orig_ip_bytes", LongType()),
    StructField("resp_pkts", LongType()),
    StructField("resp_ip_bytes", LongType()),
    StructField("ip_proto", LongType()),
    StructField("tunnel_parents", StringType()),
    StructField("orig_l2_addr", StringType()),
    StructField("resp_l2_addr", StringType()),
])

# ── ssl.log ───────────────────────────────────────────────────────────────────
SSL_SCHEMA = StructType([
    StructField("ts", DoubleType()),
    StructField("uid", StringType()),
    StructField("id.orig_h", StringType()),
    StructField("id.orig_p", LongType()),
    StructField("id.resp_h", StringType()),
    StructField("id.resp_p", LongType()),
    StructField("version", StringType()),
    StructField("cipher", StringType()),
    StructField("curve", StringType()),
    StructField("server_name", StringType()),
    StructField("resumed", StringType()),
    StructField("last_alert", StringType()),
    StructField("next_protocol", StringType()),
    StructField("established", StringType()),
    StructField("ssl_history", StringType()),
    StructField("cert_chain_fps", ArrayType(StringType())),
    StructField("client_cert_chain_fps", ArrayType(StringType())),
    StructField("subject", StringType()),
    StructField("issuer", StringType()),
    StructField("sni_matches_cert", StringType()),
    StructField("validation_status", StringType()),
    StructField("ja3", StringType()),
    StructField("ja3s", StringType()),
    StructField("orig_l2_addr", StringType()),
    StructField("resp_l2_addr", StringType()),
])

# ── x509.log ──────────────────────────────────────────────────────────────────
X509_SCHEMA = StructType([
    StructField("ts", DoubleType()),
    StructField("fingerprint", StringType()),
    StructField("certificate.version", LongType()),
    StructField("certificate.serial", StringType()),
    StructField("certificate.subject", StringType()),
    StructField("certificate.issuer", StringType()),
    StructField("certificate.not_valid_before", DoubleType()),
    StructField("certificate.not_valid_after", DoubleType()),
    StructField("certificate.key_alg", StringType()),
    StructField("certificate.sig_alg", StringType()),
    StructField("certificate.key_type", StringType()),
    StructField("certificate.key_length", LongType()),
    StructField("certificate.exponent", StringType()),
    StructField("certificate.curve", StringType()),
    StructField("san.dns", ArrayType(StringType())),
    StructField("san.uri", ArrayType(StringType())),
    StructField("san.email", ArrayType(StringType())),
    StructField("san.ip", ArrayType(StringType())),
    StructField("basic_constraints.ca", StringType()),
    StructField("basic_constraints.path_len", LongType()),
    StructField("host_cert", StringType()),
])

# ── http.log ──────────────────────────────────────────────────────────────────
HTTP_SCHEMA = StructType([
    StructField("ts", DoubleType()),
    StructField("uid", StringType()),
    StructField("id.orig_h", StringType()),
    StructField("id.orig_p", LongType()),
    StructField("id.resp_h", StringType()),
    StructField("id.resp_p", LongType()),
    StructField("trans_depth", LongType()),
    StructField("method", StringType()),
    StructField("host", StringType()),
    StructField("uri", StringType()),
    StructField("referrer", StringType()),
    StructField("version", StringType()),
    StructField("user_agent", StringType()),
    StructField("origin", StringType()),
    StructField("request_body_len", LongType()),
    StructField("response_body_len", LongType()),
    StructField("status_code", LongType()),
    StructField("status_msg", StringType()),
    StructField("info_code", LongType()),
    StructField("info_msg", StringType()),
    StructField("tags", ArrayType(StringType())),
    StructField("proxied", StringType()),
    StructField("orig_fuids", ArrayType(StringType())),
    StructField("orig_filenames", ArrayType(StringType())),
    StructField("orig_mime_types", ArrayType(StringType())),
    StructField("resp_fuids", ArrayType(StringType())),
    StructField("resp_filenames", ArrayType(StringType())),
    StructField("resp_mime_types", ArrayType(StringType())),
    StructField("orig_l2_addr", StringType()),
    StructField("resp_l2_addr", StringType()),
])

# ── dns.log ───────────────────────────────────────────────────────────────────
DNS_SCHEMA = StructType([
    StructField("ts", DoubleType()),
    StructField("uid", StringType()),
    StructField("id.orig_h", StringType()),
    StructField("id.orig_p", LongType()),
    StructField("id.resp_h", StringType()),
    StructField("id.resp_p", LongType()),
    StructField("proto", StringType()),
    StructField("trans_id", LongType()),
    StructField("rtt", DoubleType()),
    StructField("query", StringType()),
    StructField("qclass", LongType()),
    StructField("qclass_name", StringType()),
    StructField("qtype", LongType()),
    StructField("qtype_name", StringType()),
    StructField("rcode", LongType()),
    StructField("rcode_name", StringType()),
    StructField("AA", StringType()),
    StructField("TC", StringType()),
    StructField("RD", StringType()),
    StructField("RA", StringType()),
    StructField("Z", LongType()),
    StructField("answers", ArrayType(StringType())),
    StructField("TTLs", ArrayType(DoubleType())),
    StructField("rejected", StringType()),
    StructField("orig_l2_addr", StringType()),
    StructField("resp_l2_addr", StringType()),
])
